CREATE TABLE IF NOT EXISTS bookings (
    id SERIAL PRIMARY KEY,
    userId VARCHAR(255),
    userEmail VARCHAR(255),
    tourName VARCHAR(255) NOT NULL,
    fullName VARCHAR(255) NOT NULL,
    guestSize INTEGER NOT NULL,
    phone VARCHAR(20) NOT NULL,
    bookAt TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
